CREATE DATABASE IF NOT EXISTS mmwave;
USE mmwave;

CREATE TABLE IF NOT EXISTS api_tokens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE
);

INSERT IGNORE INTO api_tokens (token) VALUES ('changeme');

CREATE TABLE IF NOT EXISTS sensor_events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sensor_id VARCHAR(128) NOT NULL,
    room_name VARCHAR(128) NOT NULL,
    state TINYINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS room_status (
    room_name VARCHAR(128) PRIMARY KEY,
    state TINYINT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

